# version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: kanut-server-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  api:
    image: kanut-server:v1
    container_name: kanut-server-container
    build: .
    # command: "./bin/rails server"
    volumes:
      # - .:/app
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    # command: bash -c "bundle exec rails db:create" # TODO: Check if this will be useful and how to configure it correctly
volumes:
  postgres_data: {}
  app-storage: {}