# version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: kanut-server-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - kanut-network
  api:
    image: kanut-server:v1
    container_name: kanut-server-container
    build: .
    # command: "./bin/rails server"
    volumes:
      - .:/app # Development
      # - app-storage:/app/storage
      # - app-storage:/rails/storage # Production # TODO: Check if this is correct
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - kanut-network
    env_file:
      - ".env"
    # command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails server -b '0.0.0.0'" # TODO: Check if this will be useful and how to configure it correctly
volumes:
  postgres_data: {}
  # app-storage: {} # Production
networks:
  kanut-network:
    external: true